### ISSUE TITLE
cudaErrorInvalidValue Error

### ISSUE THREAD

**Issue by quicktwit** [morsingher/modern_mvs#1]
Hi
First of all, I would like to thank the author. I am trying this repo for my work.
I could build and convert colmap to mvs. Now when I try to run the compiler using JSON file, I am getting this error:
```
Moving data to CUDA...
CUDA error at /home/username/modern_mvs/src/cuda/texture_array.cu:19 code=1(cudaErrorInvalidValue) “cudaMallocArray(&arrays[i], &channelDesc, cols, rows)”
```
Can you help how to fix this?
Thank you in advance.

**Comment by quicktwit** [comment]
I fixed it after providing correct MAX_IMAGES.

**Comment by morsingher** [comment]
Hi @quicktwit, sorry for the delay! Removing the hard-coded MAX_IMAGES parameter is on the to-do list, but I'm glad you made it without my help and you find this repo useful :)
